### ISSUE TITLE
Create data structure in example data

### ISSUE THREAD

**Issue by AndyClifton** [IEA-Wind-Task-32/cold-climate-data-comparison#2]
At the moment all data are in the root directory. This keeps things simple, but makes it harder to see what is where.

For the demo, I wonder if it would be helpful to create a bit of structure, e.g. "/lidarData" and "/metMastData", and then move data in there. 

@MarcTask32 can you confirm that this can be done by...
1. In _ScriptTask32_CorrelationLidarMetMast_Nergica_, changing...
   1. Line 68: _str_pathDirectory_lidar_ from _""_ to _"/lidarData"_
   2. Line 77: _str_pathDirectory_CQ_ from _"./"_ to _"/metMastData"_

2. In _ScriptTask32_LidarDataAvailability_MetMast_Nergica_, changing...
   1. Line 59: _lidar_data_path_ from _"./80m_2015_dataWindCube.pkl"_ to _"./lidarData/80m_2015_dataWindCube.pkl"_
   2. Line 60: _mmv1_data_path_ from _"./*80m*.csv" to _"./metMastData/*80m*.csv"
   3. Line 61: _mmv2_data_path_ from _"./*80m*.csv" to _"./metMastData/*78m*.csv" 

If yes, I'll modify the files and commit to the [release-0.1](https://github.com/IEA-Wind-Task-32/cold-climate-data-comparison/tree/release-0.1) branch.

**Comment by MarcTask32** [comment]
Hi @AndyClifton :

I checked with the analyst who wrote the code and there is no problem to create 2 sub-folders for the Lidar and MetMast data, as long as the code is changed accordingly.

I also agree with the MIT license and the terms for use of the Nergica data.

Thank you for improving this repository!

Marc
